name: Publish to npm
#Context: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry
on:
  push:
    branches:
      - dev

jobs:
  build-and-publish:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # This makes the action check out the git commit that triggered the workflow
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Check git status
        id: git-status
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::set-output name=dirty::true"
          fi

      - name: Configure git user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit changes if any
        run: |
          git add .
          git commit -m "Build artifacts" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Bump package version and publish to npm
        run: |
          npm version minor -m "Bump version to %s [skip ci]"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
